Repository PreOnBoarding-Team17/Week4_JavaScript, pull requests merged in 2022-02, with the labels that each got.

#5 [현다솜] feat: youtube 영상 추가하기
  CSS/Youtube.css
  JS/youtube.js
  index.html
Labels: :joystick: 기능, 📱 UI

#7 [정인권] feat: Header 영역 구현
  Asset/logo.png
  Asset/mobile-logo.JPG
  Asset/profile.jpg
  Asset/shop.jpg
  CSS/GNB.css
  CSS/GlobalStyles.css
  CSS/Reset.css
  CSS/Youtube.css
  JS/GNB.js
  index.html
Labels: :joystick: 기능, 📱 UI

#11 [황상섭] 이미지 변화 슬라이더 구현
  Asset/Slider/Icon.png
  Asset/Slider/Slider_1.jpeg
  Asset/Slider/Slider_2.jpeg
  Asset/Slider/Slider_3.jpeg
  CSS/Slider.css
  JS/Slider.js
  index.html
Labels: :joystick: 기능, 📱 UI

#12 [현다솜] feat: banner 구현 + youtube iframe 수정
  Asset/banner-background-mobile.png
  Asset/banner-background.png
  Asset/banner-image-1-mobile.png
  Asset/banner-image-1.png
  Asset/banner-image-2-mobile.png
  Asset/banner-image-2.png
  CSS/Banner.css
  CSS/GlobalStyles.css
  JS/Banner.js
  JS/youtube.js
  index.html
Labels: :joystick: 기능, 📱 UI

#14 [현다솜] refactor: bundler 설치 + postcss 적용
  .babelrc.js
  .gitignore
  .postcssrc.js
  CSS/Footer.css
  CSS/GNB.css
  Static/favicon.ico
  index.html
  package-lock.json
  package.json
Labels: ⚙️ 설정, ⬆️ 리팩토링

#15 [황상섭] 모든 a 태그에 해당 홈페이지 링크 추가
  index.html
Labels: ⬆️ 리팩토링
